FROM ubuntu:21.10
ENV DEBIAN_FRONTEND="noninteractive"
RUN apt update && apt dist-upgrade -y &&\
    apt-get --no-install-recommends install -y python3-pip  &&\
    apt autoremove && \
    apt autoclean && \
    rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY requirements.txt /app
RUN pip3 install -r requirements.txt
RUN pip3 uninstall -y PyQt5
COPY rewrite/ /app/rewrite


# CMD [ "python", "/app/rewrite/runGui.py" ]