# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "baclend"
  muonic:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    # env:
    #   working-directory: ./backend
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, ubuntu-16.04, ubuntu-18.04, ubuntu-20.04, macos-10.15, macos-11.0]
        # os: [ubuntu-latest]
        python-version: [3.7, 3.8]
        # python-version: [3.7]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies

        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest pytest-cov python-coveralls coverage
          pip install -r requirements.txt
      # - name: Super-Linter
      #   uses: docker://github/super-linter:v3
      - name: Test with pytest
        shell: bash
        
        env: 
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
        run: |
          pytest rewrite/test --doctest-modules --cov --cov-append
          export COVERALLS_REPO_TOKEN=${{ secrets.COVERALLS_TOKEN }}
          COVERALLS_REPO_TOKEN=${{ secrets.COVERALLS_TOKEN }} coveralls
  
      # - name: Start SSH session
      #   uses: luchihoratiu/debug-via-ssh@main
      #   with:
      #     NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
      #     SSH_PASS: ${{ secrets.SSH_PASS }}
      - name: Coveralls
        uses: AndreMiras/coveralls-python-action@develop
        with:
          parallel: true
          flag-name: Unit Test
        
  coveralls_finish:
    needs: muonic
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: AndreMiras/coveralls-python-action@develop
      with:
        parallel-finished: true